---
title: "Run GEDI"
output:
  html_notebook:
    df_print: paged
---

```{r, message=FALSE}

library(scran)
library(scater)
library(uwot)
library(GEDI)

```

# Loading data

```{r}

sce<- readRDS("~/Documents/temp/epigenome/12_scIntegration/gedi-example/sce.rds")

table(sce$Sample)

# filtering 
sce<-sce[,sce$Sample %in% c("10x Chromium (v3)", "Seq-Well")]

table(sce$Sample)

raw_counts<- assay(sce, "counts")

table(sce$Sample)

```

Filtering out low expressed genes

```{r}

## Filtering low expressed genes ( at least 3 cells express more than 1 counts)        
sum_genes<- rowSums(raw_counts>5)
genes_use<- sum_genes>3
table(genes_use)

sce<- sce[genes_use,]

raw_counts<- assay(sce, "counts")

sce

meta<- data.frame(colData(sce))
    
```


```{r, fig.width=7, fig.height=7}

K<- 20
itelim <- 200
mode <- "Bsphere"
oi_shrinkage<- 0.001

model <- new("GEDI") # Initialize GEDI object
model$setup( Samples = sce$Sample, colData=data.frame(colData(sce)), M = raw_counts,  mode = mode, oi_shrinkage=oi_shrinkage ) # set up parameters
o_0.init <- model$hyperparams$o_0
S_o.init <- model$hyperparams$S_o
S_si.init <- model$hyperparams$S_si
model$initialize.LVs(randomSeed = 1) # initialize LVs
model$optimize(itelim) # run model

model$plotTracking()

head(colData.gedi(model) )

```


Visualize the global offset and library size factors against

```{r, fig.width=7, fig.height=7}

M<- raw_counts
smoothScatter(o_0.init,model$params$o,bandwidth = 0.05, nbin=500)
abline(0,1)
smoothScatter(log(1+rowSums(M)),o_0.init,bandwidth = 0.05, nbin=500)
smoothScatter(log(1+rowSums(M)),model$params$o,bandwidth = 0.05, nbin=500)
smoothScatter(do.call(c,model$hyperparams$si_0),do.call(c,model$params$si),bandwidth = 0.05, nbin=500)
abline(0,1)

```

Visualize dispersion

```{r, fig.width=7, fig.height=7}

dispersion <- dispersion.gedi(model)

plot_dispersion(dispersion)

```

Visualize integration results

```{r, fig.width=7, fig.height=7}

# Generating svd
svd_res <- svd.gedi( model )
embedding_res_svd<- svd_res$v %*% diag(svd_res$d)
colnames(embedding_res_svd)<- paste0("embedding", 1:ncol(embedding_res_svd))

# Generating umap of 2 dimensions
umap_2_res <- umap(embedding_res_svd, min_dist=0.01, metric="euclidean")
colnames(umap_2_res)<- paste0("umap", 1:2)
rownames(umap_2_res)<- model$aux$cellIDs
umap_2_res<- data.frame(umap_2_res)

# Reorder meta
meta<- meta[model$aux$cellIDs,] # GEDI reorders the cells by sample, so we need to reorder our original metadata

plot_embedding( umap_2_res, meta$Sample )

plot_embedding( umap_2_res, meta$CellType )

```


```{r}

sessionInfo()

```

